x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  local-database:
    container_name: relay-database
    image: postgres:18-alpine
    restart: always
    profiles:
      - dev
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: relay
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data # locally bound ".docker" folder
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # init database with SQL files from local "database" folder
    logging: *default-logging

  database:
    container_name: relay-database
    image: postgres:18-alpine
    restart: always
    profiles:
      - prod
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: relay
    ports:
      - 4000:5432
    networks:
      - relay-network
    volumes:
      - database-data:/var/lib/postgresql/data # store data from postgresql in the volume
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # init database with SQL files from local "database" folder
    logging: *default-logging

  backend:
    container_name: relay-backend
    image: fredrikj31/relay-backend:latest
    restart: always
    profiles:
      - prod
    environment:
      DATABASE_HOST: relay-database
      DATABASE_PORT: 5432 # Must be set to "5432", because the backend and database shares network
      DATABASE_NAME: relay
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      TOKEN_PASSWORD_SALT: ${TOKEN_PASSWORD_SALT}
    networks:
      - cloudflared
    ports:
      - 4002:3000
    logging: *default-logging

  frontend:
    container_name: relay-frontend
    image: fredrikj31/relay-frontend:latest
    restart: always
    profiles:
      - prod
    networks:
      - cloudflared
    ports:
      - 4003:80
    logging: *default-logging

networks:
  relay-network:
    driver: bridge
  cloudflared:
    external: true

volumes:
  database-data:
    name: relay-database-data
    driver: local
