x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    container_name: relay-frontend
    image: fredrikj31/relay-frontend:latest
    restart: always
    profiles:
      - prod
    networks:
      - cloudflared
    ports:
      - 4003:80
    logging: *default-logging

networks:
  cloudflared:
    external: true
