/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteRouteImport } from './routes/signup/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated.settings/route'
import { Route as AuthenticatedMessagesRouteRouteImport } from './routes/_authenticated.messages/route'
import { Route as AuthenticatedContactsRouteRouteImport } from './routes/_authenticated.contacts/route'
import { Route as AuthenticatedArchiveRouteRouteImport } from './routes/_authenticated.archive/route'
import { Route as AuthenticatedIndexRouteRouteImport } from './routes/_authenticated.index/route'

const SignupRouteRoute = SignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRouteRoute =
  AuthenticatedMessagesRouteRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsRouteRoute =
  AuthenticatedContactsRouteRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchiveRouteRoute =
  AuthenticatedArchiveRouteRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndexRouteRoute = AuthenticatedIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRouteRoute
  '/login': typeof LoginRouteRoute
  '/signup': typeof SignupRouteRoute
  '/archive': typeof AuthenticatedArchiveRouteRoute
  '/contacts': typeof AuthenticatedContactsRouteRoute
  '/messages': typeof AuthenticatedMessagesRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRouteRoute
  '/login': typeof LoginRouteRoute
  '/signup': typeof SignupRouteRoute
  '/archive': typeof AuthenticatedArchiveRouteRoute
  '/contacts': typeof AuthenticatedContactsRouteRoute
  '/messages': typeof AuthenticatedMessagesRouteRoute
  '/settings': typeof AuthenticatedSettingsRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/signup': typeof SignupRouteRoute
  '/_authenticated/': typeof AuthenticatedIndexRouteRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRouteRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRouteRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/archive'
    | '/contacts'
    | '/messages'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/archive'
    | '/contacts'
    | '/messages'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/'
    | '/_authenticated/archive'
    | '/_authenticated/contacts'
    | '/_authenticated/messages'
    | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
  SignupRouteRoute: typeof SignupRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRouteRoute: typeof AuthenticatedIndexRouteRoute
  AuthenticatedArchiveRouteRoute: typeof AuthenticatedArchiveRouteRoute
  AuthenticatedContactsRouteRoute: typeof AuthenticatedContactsRouteRoute
  AuthenticatedMessagesRouteRoute: typeof AuthenticatedMessagesRouteRoute
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRouteRoute: AuthenticatedIndexRouteRoute,
  AuthenticatedArchiveRouteRoute: AuthenticatedArchiveRouteRoute,
  AuthenticatedContactsRouteRoute: AuthenticatedContactsRouteRoute,
  AuthenticatedMessagesRouteRoute: AuthenticatedMessagesRouteRoute,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
  SignupRouteRoute: SignupRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
